default: &default
  adapter: mysql2
  database: mysql
  username: root
  password: Kazu0311
  host: localhost
  encoding: utf8

development:
  <<: *default

test:
  <<: *default

production:
  #<<: *default
  adapter: mysql2 
  encoding: utf8
  pool: 5 
  database: friends_production 
  username: root
  password: 
  socket: /tmp/mysql.sock