default: &default
  adapter: mysql2
  username: root
  password: Kazu0311
  host: localhost
  encoding: utf8
  pool: 5 
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: mysql_development

test:
  <<: *default
  database: mysql_test

production:
  #<<: *default
  adapter: mysql2 
  encoding: utf8
  pool: 5 
  database: friends_production 
  username: root
  password:
  #socket: /tmp/mysql.sock
  socket: /var/lib/mysql/mysql.sock